name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Get dependencies
      run: |
        pip3 install conan
        conan --version
        sudo apt update
        sudo apt install libgl-dev
    - name: Build
      run: |
        cmake .
        make Runtime
