name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get dependencies
      run: |
        pip3 install conan
        conan --version

    - name: Build
      run: |
        export CONAN_SYSREQUIRES_MODE=enabled
        cmake .
        make Runtime
