name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CONAN_SYSREQUIRES_MODE: disabled
    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Get dependencies
      run: |
        pip3 install conan
        conan --version

    - name: Build
      run: |
        cmake .
        make Runtime
